// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

var TableNames = struct {
	Asset         string
	Configuration string
	Sensor        string
}{
	Asset:         "asset",
	Configuration: "configuration",
	Sensor:        "sensor",
}
